const artifacts = [
  ["manifest.json", "experiment identity"],
  ["plan.jsonl", "paired trial plan"],
  ["episodes.jsonl", "aggregate outcomes"],
  ["report.html", "readable report"],
  ["trials/", "per-trial evidence"],
] as const;

export function ProjectWindow() {
  return (
    <figure className="min-w-0">
      <div className="overflow-hidden rounded-xl border border-line-strong bg-surface shadow-2xl shadow-black/30">
        <div className="flex min-h-12 items-center justify-between border-b border-line px-4">
          <span className="font-mono text-xs text-muted">
            scaffoldscope · offline demo
          </span>
          <span className="font-mono text-[11px] text-dim">run evidence</span>
        </div>
        <div className="grid min-w-0 lg:grid-cols-[1.35fr_0.8fr]">
          <div className="min-w-0 border-b border-line p-5 lg:border-b-0 lg:border-r">
            <div className="mb-5 flex items-center justify-between gap-4">
              <div>
                <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-dim">
                  Experiment
                </p>
                <p className="mt-1 text-sm font-medium text-ink">
                  offline-quickstart
                </p>
              </div>
              <span className="rounded-full border border-mint/30 bg-mint/8 px-2.5 py-1 font-mono text-[10px] font-medium uppercase tracking-[0.12em] text-mint">
                complete
              </span>
            </div>
            <div className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-line bg-line sm:grid-cols-3">
              <div className="bg-elevated p-3">
                <p className="font-mono text-lg font-semibold text-ink">12 / 12</p>
                <p className="mt-1 text-[11px] text-dim">recorded trials</p>
              </div>
              <div className="bg-elevated p-3">
                <p className="font-mono text-lg font-semibold text-ink">3 / 3</p>
                <p className="mt-1 text-[11px] text-dim">paired blocks</p>
              </div>
              <div className="col-span-2 bg-elevated p-3 sm:col-span-1">
                <p className="font-mono text-lg font-semibold text-ink">
                  27,477
                </p>
                <p className="mt-1 text-[11px] text-dim">recorded tokens</p>
              </div>
            </div>
            <div className="mt-5 rounded-lg border border-line bg-canvas p-4">
              <pre className="whitespace-pre-wrap break-words font-mono text-[11px] leading-6 text-muted">
                <code>
                  <span className="text-dim">$</span>{" "}
                  <span className="text-ink">scaffoldscope status</span>{" "}
                  runs/offline-quickstart-1b212f14{"\n"}
                  Progress: <span className="text-mint">12 / 12 (100.0%)</span>;
                  remaining: 0{"\n"}
                  Paired blocks: <span className="text-mint">3 / 3 (100.0%)</span>
                  {"\n"}
                  Outcomes: context_overflow=3, resolved=9{"\n"}
                  {"\n"}
                  <span className="text-dim">$</span>{" "}
                  <span className="text-ink">scaffoldscope check</span>{" "}
                  runs/offline-quickstart-1b212f14{"\n"}
                  <span className="text-mint">
                    PASS: result bundle is complete and internally consistent.
                  </span>
                </code>
              </pre>
            </div>
          </div>
          <aside aria-label="Generated evidence files" className="p-5">
            <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-dim">
              Evidence
            </p>
            <ul className="mt-3 divide-y divide-line">
              {artifacts.map(([name, description]) => (
                <li className="py-3 first:pt-1" key={name}>
                  <p className="font-mono text-xs text-ink">{name}</p>
                  <p className="mt-1 text-[11px] text-dim">{description}</p>
                </li>
              ))}
            </ul>
            <div className="mt-4 border-t border-line pt-4">
              <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-warning">
                Study warnings
              </p>
              <p className="mt-2 font-mono text-[11px] leading-5 text-muted">
                SCRIPTED_PROVIDER · LOW_TASK_COUNT · LOW_POWER
              </p>
            </div>
          </aside>
        </div>
      </div>
      <figcaption className="mt-3 text-xs leading-5 text-dim">
        Generated by the bundled offline demo. Workflow validation only—not
        model-performance evidence.
      </figcaption>
    </figure>
  );
}
